"""Add email notifications setting to users table

Revision ID: 1dd04f1a7da4
Revises: b6b983c6ea50
Create Date: 2025-05-16 13:43:53.990251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd04f1a7da4'
down_revision: Union[str, None] = 'b6b983c6ea50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_notifications_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications_enabled')
    # ### end Alembic commands ###
