"""Add tables for storing historical MLB stats to be used for analysis

Revision ID: 3758c22802f7
Revises: fc42788e644b
Create Date: 2024-10-10 16:18:28.311286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3758c22802f7'
down_revision: Union[str, None] = 'fc42788e644b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mlb_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('winning_percentage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mlb_defensive_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('team_era', sa.Float(), nullable=True),
    sa.Column('runs_allowed', sa.Integer(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('fielding_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['mlb_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mlb_offensive_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('team_batting_average', sa.Float(), nullable=True),
    sa.Column('runs_scored', sa.Integer(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('on_base_percentage', sa.Float(), nullable=True),
    sa.Column('slugging_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['mlb_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mlb_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['mlb_teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['mlb_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mlb_schedule')
    op.drop_table('mlb_offensive_stats')
    op.drop_table('mlb_defensive_stats')
    op.drop_table('mlb_teams')
    # ### end Alembic commands ###
