"""Add home team and away team columns to odds table

Revision ID: a5d3e5750b30
Revises: e36eb76ddcc7
Create Date: 2024-03-29 18:19:08.417856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d3e5750b30'
down_revision: Union[str, None] = 'e36eb76ddcc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odds', sa.Column('home_team', sa.String(), nullable=True))
    op.add_column('odds', sa.Column('away_team', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odds', 'away_team')
    op.drop_column('odds', 'home_team')
    # ### end Alembic commands ###
