"""Update defensive stats schema

Revision ID: b6b983c6ea50
Revises: 673a72133321
Create Date: 2024-10-13 13:55:11.794370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b983c6ea50'
down_revision: Union[str, None] = '673a72133321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mlb_defensive_stats', sa.Column('avg_against', sa.Float(), nullable=True))
    op.drop_column('mlb_defensive_stats', 'fielding_percentage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mlb_defensive_stats', sa.Column('fielding_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('mlb_defensive_stats', 'avg_against')
    # ### end Alembic commands ###
