"""add mlb_pitcher_stats table

Revision ID: cabafa45acd1
Revises: 1dd04f1a7da4
Create Date: 2026-08-11 20:25:13.893535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabafa45acd1'
down_revision: Union[str, None] = '1dd04f1a7da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mlb_pitcher_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('pitcher_id', sa.Integer(), nullable=True),
    sa.Column('pitcher_name', sa.String(), nullable=True),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.Column('k9', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['mlb_schedule.game_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['mlb_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_id', name='uq_pitcher_stats_game_team')
    )
    op.create_index(op.f('ix_mlb_pitcher_stats_game_id'), 'mlb_pitcher_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_mlb_pitcher_stats_pitcher_id'), 'mlb_pitcher_stats', ['pitcher_id'], unique=False)
    op.create_index(op.f('ix_mlb_pitcher_stats_team_id'), 'mlb_pitcher_stats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mlb_pitcher_stats_team_id'), table_name='mlb_pitcher_stats')
    op.drop_index(op.f('ix_mlb_pitcher_stats_pitcher_id'), table_name='mlb_pitcher_stats')
    op.drop_index(op.f('ix_mlb_pitcher_stats_game_id'), table_name='mlb_pitcher_stats')
    op.drop_table('mlb_pitcher_stats')
    # ### end Alembic commands ###
