"""Add sport column

Revision ID: fc42788e644b
Revises: 9129c62b33df
Create Date: 2024-08-07 17:32:31.888905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc42788e644b'
down_revision: Union[str, None] = '9129c62b33df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odds', sa.Column('sport', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odds', 'sport')
    # ### end Alembic commands ###
