name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    env:
      ODDS_API_URL: ${{ secrets.ODDS_API_URL }}
      DB_URL: ${{ secrets.DB_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 
      with:
        python-version: '3.9'
        check-latest: true
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
    - name: Run tests and generate coverage report
      run: cd api/tests && coverage run -m pytest && coverage report -m

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      with:
        persist-credentials: false
    - name: Use Node.js
      uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    - name: Install dependencies
      run: cd frontend && npm ci
    - name: Run tests and generate coverage report
      run: cd frontend && npm run test:full